development:
  adapter: postgresql
  encoding: unicode
  database: mksdrive-dev
  pool: 5
  username: 
  password:


test:
  adapter: postgresql
  encoding: unicode
  database: mksdrive-test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: mksdrive-production
  pool: 5
  username: 
  password:
